// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteNumericAttributesBeforeBlockStmt, err = db.PrepareContext(ctx, deleteNumericAttributesBeforeBlock); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNumericAttributesBeforeBlock: %w", err)
	}
	if q.deletePayloadsBeforeBlockStmt, err = db.PrepareContext(ctx, deletePayloadsBeforeBlock); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePayloadsBeforeBlock: %w", err)
	}
	if q.deleteStringAttributesBeforeBlockStmt, err = db.PrepareContext(ctx, deleteStringAttributesBeforeBlock); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteStringAttributesBeforeBlock: %w", err)
	}
	if q.getCreatorStmt, err = db.PrepareContext(ctx, getCreator); err != nil {
		return nil, fmt.Errorf("error preparing query GetCreator: %w", err)
	}
	if q.getLastBlockStmt, err = db.PrepareContext(ctx, getLastBlock); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastBlock: %w", err)
	}
	if q.getOldNumericAttributesStmt, err = db.PrepareContext(ctx, getOldNumericAttributes); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldNumericAttributes: %w", err)
	}
	if q.getOldNumericAttributesForToBlockChangeStmt, err = db.PrepareContext(ctx, getOldNumericAttributesForToBlockChange); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldNumericAttributesForToBlockChange: %w", err)
	}
	if q.getOldPayloadsStmt, err = db.PrepareContext(ctx, getOldPayloads); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldPayloads: %w", err)
	}
	if q.getOldPayloadsForToBlockChangeStmt, err = db.PrepareContext(ctx, getOldPayloadsForToBlockChange); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldPayloadsForToBlockChange: %w", err)
	}
	if q.getOldStringAttributesStmt, err = db.PrepareContext(ctx, getOldStringAttributes); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldStringAttributes: %w", err)
	}
	if q.getOldStringAttributesForToBlockChangeStmt, err = db.PrepareContext(ctx, getOldStringAttributesForToBlockChange); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldStringAttributesForToBlockChange: %w", err)
	}
	if q.insertNumericAttributeStmt, err = db.PrepareContext(ctx, insertNumericAttribute); err != nil {
		return nil, fmt.Errorf("error preparing query InsertNumericAttribute: %w", err)
	}
	if q.insertPayloadStmt, err = db.PrepareContext(ctx, insertPayload); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPayload: %w", err)
	}
	if q.insertStringAttributeStmt, err = db.PrepareContext(ctx, insertStringAttribute); err != nil {
		return nil, fmt.Errorf("error preparing query InsertStringAttribute: %w", err)
	}
	if q.terminateNumericAttributesAtBlockStmt, err = db.PrepareContext(ctx, terminateNumericAttributesAtBlock); err != nil {
		return nil, fmt.Errorf("error preparing query TerminateNumericAttributesAtBlock: %w", err)
	}
	if q.terminatePayloadsAtBlockStmt, err = db.PrepareContext(ctx, terminatePayloadsAtBlock); err != nil {
		return nil, fmt.Errorf("error preparing query TerminatePayloadsAtBlock: %w", err)
	}
	if q.terminateStringAttributesAtBlockStmt, err = db.PrepareContext(ctx, terminateStringAttributesAtBlock); err != nil {
		return nil, fmt.Errorf("error preparing query TerminateStringAttributesAtBlock: %w", err)
	}
	if q.upsertLastBlockStmt, err = db.PrepareContext(ctx, upsertLastBlock); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertLastBlock: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteNumericAttributesBeforeBlockStmt != nil {
		if cerr := q.deleteNumericAttributesBeforeBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNumericAttributesBeforeBlockStmt: %w", cerr)
		}
	}
	if q.deletePayloadsBeforeBlockStmt != nil {
		if cerr := q.deletePayloadsBeforeBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePayloadsBeforeBlockStmt: %w", cerr)
		}
	}
	if q.deleteStringAttributesBeforeBlockStmt != nil {
		if cerr := q.deleteStringAttributesBeforeBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStringAttributesBeforeBlockStmt: %w", cerr)
		}
	}
	if q.getCreatorStmt != nil {
		if cerr := q.getCreatorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCreatorStmt: %w", cerr)
		}
	}
	if q.getLastBlockStmt != nil {
		if cerr := q.getLastBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastBlockStmt: %w", cerr)
		}
	}
	if q.getOldNumericAttributesStmt != nil {
		if cerr := q.getOldNumericAttributesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldNumericAttributesStmt: %w", cerr)
		}
	}
	if q.getOldNumericAttributesForToBlockChangeStmt != nil {
		if cerr := q.getOldNumericAttributesForToBlockChangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldNumericAttributesForToBlockChangeStmt: %w", cerr)
		}
	}
	if q.getOldPayloadsStmt != nil {
		if cerr := q.getOldPayloadsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldPayloadsStmt: %w", cerr)
		}
	}
	if q.getOldPayloadsForToBlockChangeStmt != nil {
		if cerr := q.getOldPayloadsForToBlockChangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldPayloadsForToBlockChangeStmt: %w", cerr)
		}
	}
	if q.getOldStringAttributesStmt != nil {
		if cerr := q.getOldStringAttributesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldStringAttributesStmt: %w", cerr)
		}
	}
	if q.getOldStringAttributesForToBlockChangeStmt != nil {
		if cerr := q.getOldStringAttributesForToBlockChangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldStringAttributesForToBlockChangeStmt: %w", cerr)
		}
	}
	if q.insertNumericAttributeStmt != nil {
		if cerr := q.insertNumericAttributeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertNumericAttributeStmt: %w", cerr)
		}
	}
	if q.insertPayloadStmt != nil {
		if cerr := q.insertPayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPayloadStmt: %w", cerr)
		}
	}
	if q.insertStringAttributeStmt != nil {
		if cerr := q.insertStringAttributeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertStringAttributeStmt: %w", cerr)
		}
	}
	if q.terminateNumericAttributesAtBlockStmt != nil {
		if cerr := q.terminateNumericAttributesAtBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing terminateNumericAttributesAtBlockStmt: %w", cerr)
		}
	}
	if q.terminatePayloadsAtBlockStmt != nil {
		if cerr := q.terminatePayloadsAtBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing terminatePayloadsAtBlockStmt: %w", cerr)
		}
	}
	if q.terminateStringAttributesAtBlockStmt != nil {
		if cerr := q.terminateStringAttributesAtBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing terminateStringAttributesAtBlockStmt: %w", cerr)
		}
	}
	if q.upsertLastBlockStmt != nil {
		if cerr := q.upsertLastBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertLastBlockStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                          DBTX
	tx                                          *sql.Tx
	deleteNumericAttributesBeforeBlockStmt      *sql.Stmt
	deletePayloadsBeforeBlockStmt               *sql.Stmt
	deleteStringAttributesBeforeBlockStmt       *sql.Stmt
	getCreatorStmt                              *sql.Stmt
	getLastBlockStmt                            *sql.Stmt
	getOldNumericAttributesStmt                 *sql.Stmt
	getOldNumericAttributesForToBlockChangeStmt *sql.Stmt
	getOldPayloadsStmt                          *sql.Stmt
	getOldPayloadsForToBlockChangeStmt          *sql.Stmt
	getOldStringAttributesStmt                  *sql.Stmt
	getOldStringAttributesForToBlockChangeStmt  *sql.Stmt
	insertNumericAttributeStmt                  *sql.Stmt
	insertPayloadStmt                           *sql.Stmt
	insertStringAttributeStmt                   *sql.Stmt
	terminateNumericAttributesAtBlockStmt       *sql.Stmt
	terminatePayloadsAtBlockStmt                *sql.Stmt
	terminateStringAttributesAtBlockStmt        *sql.Stmt
	upsertLastBlockStmt                         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		deleteNumericAttributesBeforeBlockStmt: q.deleteNumericAttributesBeforeBlockStmt,
		deletePayloadsBeforeBlockStmt:          q.deletePayloadsBeforeBlockStmt,
		deleteStringAttributesBeforeBlockStmt:  q.deleteStringAttributesBeforeBlockStmt,
		getCreatorStmt:                         q.getCreatorStmt,
		getLastBlockStmt:                       q.getLastBlockStmt,
		getOldNumericAttributesStmt:            q.getOldNumericAttributesStmt,
		getOldNumericAttributesForToBlockChangeStmt: q.getOldNumericAttributesForToBlockChangeStmt,
		getOldPayloadsStmt:                          q.getOldPayloadsStmt,
		getOldPayloadsForToBlockChangeStmt:          q.getOldPayloadsForToBlockChangeStmt,
		getOldStringAttributesStmt:                  q.getOldStringAttributesStmt,
		getOldStringAttributesForToBlockChangeStmt:  q.getOldStringAttributesForToBlockChangeStmt,
		insertNumericAttributeStmt:                  q.insertNumericAttributeStmt,
		insertPayloadStmt:                           q.insertPayloadStmt,
		insertStringAttributeStmt:                   q.insertStringAttributeStmt,
		terminateNumericAttributesAtBlockStmt:       q.terminateNumericAttributesAtBlockStmt,
		terminatePayloadsAtBlockStmt:                q.terminatePayloadsAtBlockStmt,
		terminateStringAttributesAtBlockStmt:        q.terminateStringAttributesAtBlockStmt,
		upsertLastBlockStmt:                         q.upsertLastBlockStmt,
	}
}
