// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

type LastBlock struct {
	ID    int64
	Block int64
}

type NumericAttribute struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     Uint64
}

type Payload struct {
	EntityKey         []byte
	FromBlock         int64
	ToBlock           int64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

type StringAttribute struct {
	EntityKey []byte
	FromBlock int64
	ToBlock   int64
	Key       string
	Value     string
}
