// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type LastBlock struct {
	ID    int64
	Block int64
}

type NumericAttribute struct {
	EntityKey []byte
	FromBlock Uint64
	ToBlock   Uint64
	Key       string
	Value     Uint64
}

type Payload struct {
	EntityKey         []byte
	FromBlock         Uint64
	ToBlock           Uint64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

type StringAttribute struct {
	EntityKey []byte
	FromBlock Uint64
	ToBlock   Uint64
	Key       string
	Value     string
}
