// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	DeleteNumericAttributesBeforeBlock(ctx context.Context, fromBlock Uint64) error
	DeletePayloadsBeforeBlock(ctx context.Context, fromBlock Uint64) error
	DeleteStringAttributesBeforeBlock(ctx context.Context, fromBlock Uint64) error
	GetCreator(ctx context.Context, arg GetCreatorParams) (string, error)
	GetLastBlock(ctx context.Context) (int64, error)
	GetLatestPayload(ctx context.Context, entityKey []byte) (GetLatestPayloadRow, error)
	InsertNumericAttribute(ctx context.Context, arg InsertNumericAttributeParams) error
	InsertPayload(ctx context.Context, arg InsertPayloadParams) error
	InsertStringAttribute(ctx context.Context, arg InsertStringAttributeParams) error
	TerminateNumericAttributesAtBlock(ctx context.Context, arg TerminateNumericAttributesAtBlockParams) error
	// TerminateEntityAtBlock is split into 3 separate queries for SQLite compatibility
	TerminatePayloadsAtBlock(ctx context.Context, arg TerminatePayloadsAtBlockParams) error
	TerminateStringAttributesAtBlock(ctx context.Context, arg TerminateStringAttributesAtBlockParams) error
	UpsertLastBlock(ctx context.Context, block int64) error
}

var _ Querier = (*Queries)(nil)
