// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const deleteNumericAttributesBeforeBlock = `-- name: DeleteNumericAttributesBeforeBlock :exec
DELETE FROM numeric_attributes
WHERE from_block < ?
`

func (q *Queries) DeleteNumericAttributesBeforeBlock(ctx context.Context, fromBlock Uint64) error {
	_, err := q.exec(ctx, q.deleteNumericAttributesBeforeBlockStmt, deleteNumericAttributesBeforeBlock, fromBlock)
	return err
}

const deletePayloadsBeforeBlock = `-- name: DeletePayloadsBeforeBlock :exec
DELETE FROM payloads
WHERE from_block < ?
`

func (q *Queries) DeletePayloadsBeforeBlock(ctx context.Context, fromBlock Uint64) error {
	_, err := q.exec(ctx, q.deletePayloadsBeforeBlockStmt, deletePayloadsBeforeBlock, fromBlock)
	return err
}

const deleteStringAttributesBeforeBlock = `-- name: DeleteStringAttributesBeforeBlock :exec
DELETE FROM string_attributes
WHERE from_block < ?
`

func (q *Queries) DeleteStringAttributesBeforeBlock(ctx context.Context, fromBlock Uint64) error {
	_, err := q.exec(ctx, q.deleteStringAttributesBeforeBlockStmt, deleteStringAttributesBeforeBlock, fromBlock)
	return err
}

const getCreator = `-- name: GetCreator :one
SELECT value FROM string_attributes
WHERE entity_key = ? AND key = '$creator' AND from_block <= ?
ORDER BY from_block DESC
LIMIT 1
`

type GetCreatorParams struct {
	EntityKey []byte
	FromBlock Uint64
}

func (q *Queries) GetCreator(ctx context.Context, arg GetCreatorParams) (string, error) {
	row := q.queryRow(ctx, q.getCreatorStmt, getCreator, arg.EntityKey, arg.FromBlock)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getLastBlock = `-- name: GetLastBlock :one
SELECT block FROM last_block
`

func (q *Queries) GetLastBlock(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getLastBlockStmt, getLastBlock)
	var block int64
	err := row.Scan(&block)
	return block, err
}

const getLatestPayload = `-- name: GetLatestPayload :one
SELECT from_block, to_block AS old_to_block, payload, content_type, string_attributes, numeric_attributes
FROM payloads
WHERE entity_key = ? ORDER BY from_block DESC LIMIT 1
`

type GetLatestPayloadRow struct {
	FromBlock         Uint64
	OldToBlock        Uint64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

func (q *Queries) GetLatestPayload(ctx context.Context, entityKey []byte) (GetLatestPayloadRow, error) {
	row := q.queryRow(ctx, q.getLatestPayloadStmt, getLatestPayload, entityKey)
	var i GetLatestPayloadRow
	err := row.Scan(
		&i.FromBlock,
		&i.OldToBlock,
		&i.Payload,
		&i.ContentType,
		&i.StringAttributes,
		&i.NumericAttributes,
	)
	return i, err
}

const insertNumericAttribute = `-- name: InsertNumericAttribute :exec
INSERT INTO numeric_attributes (
    entity_key,
    from_block,
    to_block,
    key,
    value
) VALUES (?, ?, ?, ?, ?)
`

type InsertNumericAttributeParams struct {
	EntityKey []byte
	FromBlock Uint64
	ToBlock   Uint64
	Key       string
	Value     Uint64
}

func (q *Queries) InsertNumericAttribute(ctx context.Context, arg InsertNumericAttributeParams) error {
	_, err := q.exec(ctx, q.insertNumericAttributeStmt, insertNumericAttribute,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Key,
		arg.Value,
	)
	return err
}

const insertPayload = `-- name: InsertPayload :exec
INSERT INTO payloads (
    entity_key,
    from_block,
    to_block,
    payload,
    content_type,
    string_attributes,
    numeric_attributes
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPayloadParams struct {
	EntityKey         []byte
	FromBlock         Uint64
	ToBlock           Uint64
	Payload           []byte
	ContentType       string
	StringAttributes  string
	NumericAttributes string
}

func (q *Queries) InsertPayload(ctx context.Context, arg InsertPayloadParams) error {
	_, err := q.exec(ctx, q.insertPayloadStmt, insertPayload,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Payload,
		arg.ContentType,
		arg.StringAttributes,
		arg.NumericAttributes,
	)
	return err
}

const insertStringAttribute = `-- name: InsertStringAttribute :exec
INSERT INTO string_attributes (
    entity_key,
    from_block,
    to_block,
    key,
    value
) VALUES (?, ?, ?, ?, ?)
`

type InsertStringAttributeParams struct {
	EntityKey []byte
	FromBlock Uint64
	ToBlock   Uint64
	Key       string
	Value     string
}

func (q *Queries) InsertStringAttribute(ctx context.Context, arg InsertStringAttributeParams) error {
	_, err := q.exec(ctx, q.insertStringAttributeStmt, insertStringAttribute,
		arg.EntityKey,
		arg.FromBlock,
		arg.ToBlock,
		arg.Key,
		arg.Value,
	)
	return err
}

const terminateNumericAttributesAtBlock = `-- name: TerminateNumericAttributesAtBlock :exec
UPDATE numeric_attributes
SET to_block = ?1
WHERE entity_key = ?2 AND from_block = ?3
`

type TerminateNumericAttributesAtBlockParams struct {
	ToBlock   Uint64
	EntityKey []byte
	FromBlock Uint64
}

func (q *Queries) TerminateNumericAttributesAtBlock(ctx context.Context, arg TerminateNumericAttributesAtBlockParams) error {
	_, err := q.exec(ctx, q.terminateNumericAttributesAtBlockStmt, terminateNumericAttributesAtBlock, arg.ToBlock, arg.EntityKey, arg.FromBlock)
	return err
}

const terminatePayloadsAtBlock = `-- name: TerminatePayloadsAtBlock :exec
UPDATE payloads
SET to_block = ?1
WHERE entity_key = ?2 AND from_block = ?3
`

type TerminatePayloadsAtBlockParams struct {
	ToBlock   Uint64
	EntityKey []byte
	FromBlock Uint64
}

// TerminateEntityAtBlock is split into 3 separate queries for SQLite compatibility
func (q *Queries) TerminatePayloadsAtBlock(ctx context.Context, arg TerminatePayloadsAtBlockParams) error {
	_, err := q.exec(ctx, q.terminatePayloadsAtBlockStmt, terminatePayloadsAtBlock, arg.ToBlock, arg.EntityKey, arg.FromBlock)
	return err
}

const terminateStringAttributesAtBlock = `-- name: TerminateStringAttributesAtBlock :exec
UPDATE string_attributes
SET to_block = ?1
WHERE entity_key = ?2 AND from_block = ?3
`

type TerminateStringAttributesAtBlockParams struct {
	ToBlock   Uint64
	EntityKey []byte
	FromBlock Uint64
}

func (q *Queries) TerminateStringAttributesAtBlock(ctx context.Context, arg TerminateStringAttributesAtBlockParams) error {
	_, err := q.exec(ctx, q.terminateStringAttributesAtBlockStmt, terminateStringAttributesAtBlock, arg.ToBlock, arg.EntityKey, arg.FromBlock)
	return err
}

const upsertLastBlock = `-- name: UpsertLastBlock :exec
INSERT INTO last_block (id, block)
VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET block = EXCLUDED.block
`

func (q *Queries) UpsertLastBlock(ctx context.Context, block int64) error {
	_, err := q.exec(ctx, q.upsertLastBlockStmt, upsertLastBlock, block)
	return err
}
